# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-07-04 02:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=300)),
                ('cast', models.TextField(max_length=300)),
                ('review', models.TextField(max_length=300)),
            ],
        ),
    ]
